version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: True
    ports:
      - "3306:3306"

  flask:
    build:
      context: ./flask-server
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db

  react:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      REACT_APP_ROUTE_URL: https://${HOST}/api
    depends_on:
      - flask

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    environment:
      HOST: ${HOST}
    depends_on:
      - flask
      - react